// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fmlogit_obs_cpp
Rcpp::NumericVector fmlogit_obs_cpp(const Eigen::Map<Eigen::MatrixXd>& X, const Eigen::Map<Eigen::MatrixXd>& y, Eigen::VectorXd beta0);
RcppExport SEXP _fmlogit_fmlogit_obs_cpp(SEXP XSEXP, SEXP ySEXP, SEXP beta0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type y(ySEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type beta0(beta0SEXP);
    rcpp_result_gen = Rcpp::wrap(fmlogit_obs_cpp(X, y, beta0));
    return rcpp_result_gen;
END_RCPP
}
// fmlogit_obs_grad_cpp
Rcpp::NumericMatrix fmlogit_obs_grad_cpp(const Eigen::Map<Eigen::MatrixXd>& X, const Eigen::Map<Eigen::MatrixXd>& y, Eigen::VectorXd beta0);
RcppExport SEXP _fmlogit_fmlogit_obs_grad_cpp(SEXP XSEXP, SEXP ySEXP, SEXP beta0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type y(ySEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type beta0(beta0SEXP);
    rcpp_result_gen = Rcpp::wrap(fmlogit_obs_grad_cpp(X, y, beta0));
    return rcpp_result_gen;
END_RCPP
}
// fmlogit_fast_cpp
Rcpp::List fmlogit_fast_cpp(const Eigen::Map<Eigen::MatrixXd>& X, const Eigen::Map<Eigen::MatrixXd>& y, Eigen::VectorXd beta0, int maxit, double abstol, bool verbose, double eps_g);
RcppExport SEXP _fmlogit_fmlogit_fast_cpp(SEXP XSEXP, SEXP ySEXP, SEXP beta0SEXP, SEXP maxitSEXP, SEXP abstolSEXP, SEXP verboseSEXP, SEXP eps_gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type y(ySEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< double >::type eps_g(eps_gSEXP);
    rcpp_result_gen = Rcpp::wrap(fmlogit_fast_cpp(X, y, beta0, maxit, abstol, verbose, eps_g));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fmlogit_fmlogit_obs_cpp", (DL_FUNC) &_fmlogit_fmlogit_obs_cpp, 3},
    {"_fmlogit_fmlogit_obs_grad_cpp", (DL_FUNC) &_fmlogit_fmlogit_obs_grad_cpp, 3},
    {"_fmlogit_fmlogit_fast_cpp", (DL_FUNC) &_fmlogit_fmlogit_fast_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_fmlogit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
