# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fmlogit_obs_cpp <- function(X, y, beta0) {
    .Call(`_fmlogit_fmlogit_obs_cpp`, X, y, beta0)
}

fmlogit_obs_grad_cpp <- function(X, y, beta0) {
    .Call(`_fmlogit_fmlogit_obs_grad_cpp`, X, y, beta0)
}

fmlogit_fast_cpp <- function(X, y, beta0, maxit, abstol, verbose = FALSE, eps_g = 1e-5) {
    .Call(`_fmlogit_fmlogit_fast_cpp`, X, y, beta0, maxit, abstol, verbose, eps_g)
}

